### ISSUE TITLE
Checkout Process

### ISSUE THREAD

**Issue by hoanhan101** [bennington-hardware-hacking-2019/pos_system#23]
Hugh really needs it to work

**Comment by awbry** [comment]
I barely started but this commit: 42b3e6e56b6fd333a0842c2e613869e30c4c52d1 touches the checkout process

**Comment by julianlambert** [comment]
#17 is related

**Comment by awbry** [comment]
What we have left to do on checkout side:
- [x] get stripe api working (#36)
- [x] figure out card ➡️ email data #19 #20 
- [ ] flask endpoint for receipt page to load
- [ ] #18 UI jinja/css template for receipt page
- [ ] make it so the cart lists the total throughout!
- [x] #17 refine the "cart_response" socket response so it works with the UI (might not be necessary)
- [x] #18 UI jinja/css template for confirm payment

**Comment by hoanhan101** [comment]
fixed most of them in #37. need to reconsider the work items above and open a separate issue if needed
